sudo: required
language: python
python:
    - 3.5
services:
  - docker
before_install:
  - pip install --pre -r dev-requirements.txt
install:
  - pip install .
script:
  - pyflakes dockerspawner
  - docker build -t jupyterhub/singleuser singleuser
  - docker build -t jupyterhub/systemuser systemuser
  - travis_retry py.test --cov dockerspawner tests -v
